apps/towns/urls.py
from django.conf.urls import patterns, url

from apps.towns import views

urlpatterns = patterns('',
    #Tavern views
    url(r'^tavern/$', views.tavern, name='tavern'),
    url(r'^outskirts/$', views.outskirts, name='outskirts'),
    url(r'^outskirt/(?P<outskirt_id>\d+)/$', views.outskirt_info, name='outskirt_info'),
    url(r'^tavern/hero/(?P<tavernhero_id>\d+)/$', views.tavern_hero_info, name='tavern_hero_info'),
    
    #town info
    url(r'^town/(?P<slug>[\w-]+)/$', views.town_info, name='town_info'),
)
    

config/urls.py
from django.conf.urls import patterns, include, url

from django.conf import settings

#from django.contrib import admin
#admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('apps.users.urls')),
    url(r'^', include('apps.towns.urls')),
    url(r'^', include('apps.heroes.urls')),
    url(r'^', include('apps.features.urls')),
)

#if settings.DEBUG:
    #urlpatterns += patterns('django.views.static',
        #(r'media/(?P<path>.*)', 'serve', {'document_root': settings.MEDIA_ROOT}),
    #)

apps/heroes/models.py
from django.db import models
from django.utils.timezone import utc
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
#from django.template import defaultfilters


from apps.elements.models import VersionControl
#import apps.towns.models as apps_towns

import random
from collections import OrderedDict, namedtuple
from datetime import datetime, timedelta


class HeroMathValues(VersionControl):
    """ Holds numbers used in hero related equations and functions. to balance and provide a smooth system """
    
    #base values
    base_stamina = models.IntegerField()                    #base stamina of a hero (used for calculating max stamina)
    base_hitpoints = models.IntegerField()                  #base hitpoints (increased by heroes hitpoints stat
    base_cargo = models.IntegerField()                      #base volume a hero can carry
    
    
    #hero % per point
    hitpoints_per_point = models.FloatField()
    critical_per_point = models.FloatField()
    power_per_point = models.FloatField()
    defense_per_point = models.FloatField()
    block_per_point = models.FloatField()
    hit_chance_per_point = models.FloatField()

    #Trading/Transport Stats
    speed_per_point = models.FloatField()
    cargo_per_point = models.FloatField()
    reputation_per_point = models.FloatField()
    trade_orders_per_point = models.FloatField()
    tax_reduction_per_point = models.FloatField()
    contracts_per_point = models.FloatField()

    #Craftin/Gathering
    crafting_per_point = models.FloatField()
    efficiency_per_point= models.FloatField()
    stamina_per_point = models.FloatField()
    gathering_per_point = models.FloatField()
    endurance_per_point = models.FloatField()
    luck_per_point = models.FloatField()

    
    



class HeroName(models.Model):
    """ list of random names to give heroes """
    
    name = models.CharField(max_length=63)
    
    def __unicode__(self):
        return self.name




class StatPerLevel(models.Model):
    """ to calculate stats per level """
    
    VERY_BAD = "very_bad"
    BAD = "bad"
    DECENT = "decent"
    GOOD = "good"
    EXCELLENT = "excellent"
    QUALITY = (
        (VERY_BAD, "Very Bad"),
        (BAD, "Bad"),
        (DECENT, "Decent"),
        (GOOD, "Good"),
        (EXCELLENT, "Excellent"),
    )

    #Warrior Attributes
    #STRENGTH = "strength"
    HITPOINTS = "hitpoints"
    CRITICAL = "critical"
    POWER = "power"
    DEFENSE = "defense"
    BLOCK = "block"
    HIT_CHANCE = "hit_chance"
    #Trader Attributes
    #CHARISMA = "charisma"
    SPEED = "speed"
    CARGO = "cargo"                             #volume increase
    REPUTATION = "reputation"                           
    TRADE_ORDERS = "trade_orders"
    TAX_REDUCTION = "tax_reduction"
    CONTRACTS = "contracts"
    #Crafter Attributes
    #WISDOM = "wisdom"
    CRAFTING = "crafting"
    EFFICIENCY = "efficiency"
    STAMINA = "stamina"
    GATHERING = "gathering"
    ENDURANCE = "endurance"
    LUCK = "luck"
    ATTRIBUTES = (
        #(STRENGTH, "Strength"),
        (HITPOINTS, "Hitpoints"),
        (CRITICAL, "Critical"),
        (POWER, "Power"),
        (DEFENSE, "Defense"),
        (BLOCK, "Block"),
        (HIT_CHANCE, "Hit Chance"),
        #(CHARISMA, "Charisma"),
        (SPEED, "Speed"),
        (CARGO, "Cargo"),
        (REPUTATION, "Reputation"),
        (TRADE_ORDERS, "Trade Orders"),
        (TAX_REDUCTION, "Tax Reduction"),
        (CONTRACTS, "Contracts"),
        #(WISDOM, "Wisdom"),
        (CRAFTING, "Crafting"),
        (EFFICIENCY, "Efficiency"),
        (STAMINA, "Stamina"),
        (GATHERING, "Gathering"),
        (ENDURANCE, "Endurance"),
        (LUCK, "Luck"),
    )
    
    quality = models.CharField(max_length=31, choices=QUALITY)
    attribute = models.CharField(max_length=31, choices=ATTRIBUTES)
    start_value = models.IntegerField()
    multiplier = models.FloatField()
    level_bonus = models.FloatField()
    
    class Meta:
        unique_together = ["quality", "attribute"]
        
    
    def __unicode__(self):
        return "%s: %s" % (self.attribute, self.quality)
    
    
    #calculate score based on hero level
    def level_score(self, level):
        sum_level = level * (level + 1) / 2                         # 1 + 2 + 3 +.... +n
        bonus_level = self.level_bonus * level
        result =  int(round((sum_level + bonus_level) * self.multiplier + self.start_value, 0))
        return result
    




class Hero(models.Model):
    """ player heroes. Used to perform allsorts of actions """
    
    #general stats
    name = models.CharField(max_length=63, blank=True)
    town = models.ForeignKey('towns.Town', null=True)    
    user = models.ForeignKey(User, null=True)
    xp = models.IntegerField(default=0)
    level = models.IntegerField(default=1)
    created = models.DateTimeField(null=True)
    
    #Combat Stats
    hitpoints = models.ForeignKey(StatPerLevel, null=True, related_name="+")
    critical = models.ForeignKey(StatPerLevel, null=True, related_name="+")
    power = models.ForeignKey(StatPerLevel, null=True, related_name="+")
    defense = models.ForeignKey(StatPerLevel, null=True, related_name="+")
    block = models.ForeignKey(StatPerLevel, null=True, related_name="+")
    hit_chance = models.ForeignKey(StatPerLevel, null=True, related_name="+")

    #Trading/Transport Stats
    speed = models.ForeignKey(StatPerLevel, null=True, related_name="+")
    cargo = models.ForeignKey(StatPerLevel, null=True, related_name="+")
    reputation = models.ForeignKey(StatPerLevel, null=True, related_name="+")
    trade_orders = models.ForeignKey(StatPerLevel, null=True, related_name="+")
    tax_reduction = models.ForeignKey(StatPerLevel, null=True, related_name="+")
    contracts = models.ForeignKey(StatPerLevel, null=True, related_name="+")

    #Craftin/Gathering
    crafting = models.ForeignKey(StatPerLevel, null=True, related_name="+")
    efficiency = models.ForeignKey(StatPerLevel, null=True, related_name="+")
    stamina = models.ForeignKey(StatPerLevel, null=True, related_name="+")
    gathering = models.ForeignKey(StatPerLevel, null=True, related_name="+")
    endurance = models.ForeignKey(StatPerLevel, null=True, related_name="+")
    luck = models.ForeignKey(StatPerLevel, null=True, related_name="+")

    #job attributes
    stamina_current = models.IntegerField(null=True)
    hitpoints_current = models.IntegerField(null=True)
    
    #items
    hand = models.OneToOneField("elements.Equipment", related_name="+", null=True)
    chest = models.OneToOneField("elements.Equipment", related_name="+", null=True)
    trinket = models.OneToOneField("elements.Equipment", related_name="+", null=True)
    transport = models.OneToOneField("elements.Equipment", related_name="+", null=True)
    
    
    
    def __unicode__(self):
        return "Hero"
    
    
    #return fields related to combat
    @staticmethod
    def combat_attributes():
        fields = ["hitpoints", "hit_chance", "power", "critical", "defense", "block"]
        return fields
    
    #return fields related to trade and transport
    @staticmethod
    def trade_attributes():
        fields = ["cargo", "reputation", "speed", "trade_orders", "contracts", "tax_reduction"]
        return fields
    
    #retun fields relatedtocrafting and gathering
    @staticmethod
    def craft_attributes():
        fields = ["crafting", "efficiency", "stamina", "gathering", "endurance", "luck"]
        return fields
        
    #returns all attribute fields
    @staticmethod
    def all_attributes_fields():
        combat = Hero.combat_attributes()
        trade = Hero.trade_attributes()
        craft = Hero.craft_attributes()
        return combat + trade + craft
    
    
############ HERO CREATION #################
    
    #return a random StatsPerLevel object based on attribute
    @staticmethod
    def random_quality(attribute):
        stat = StatPerLevel.objects.filter(attribute=attribute).order_by("?")[0]
        return stat

    #get a random hero name
    @staticmethod
    def random_hero_name():
        return HeroName.objects.all().order_by("?")[0].name
    
    #Generate a random hero template
    #These will be used as buyable objects in a tavern. And will be the source of player actions
    @staticmethod
    def create_random_hero():
        all_attributes = Hero.all_attributes_fields()
        hero = Hero.objects.create()
        
        for field in all_attributes:
            setattr(hero, field, Hero.random_quality(field))
        
        #add current stamina and hitpoints
        hero.hitpoints_current = hero.total_hitpoints()
        hero.stamina_current = hero.total_stamina()
        hero.save()
        
        return hero
    
    # set a combination of fields+ values for a new hero
    # example of fields: [["crafting_speed", decent], ["efficiency", bad], ["multitasking", ver_bad], ["gathering_speed", decent], ["endurance", bad], ["luck", very_bad]]
    def set_hero_starting_attributes(self, fields):
        for field in fields:
            value = StatPerLevel.objects.get(attribute=field[0], quality=field[1])
            setattr(self, field[0], value)
        self.save()
        
        
####### HERO VIEW FUNCTIONS ###########
    #get attribute value
    @staticmethod
    def get_attribute_scores():
        scores = {}
        scores[StatPerLevel.VERY_BAD] = -2
        scores[StatPerLevel.BAD] = -1
        scores[StatPerLevel.DECENT] = 0 
        scores[StatPerLevel.GOOD] = 1
        scores[StatPerLevel.EXCELLENT] = 2
        return scores
        
    #simplified quality view for a hero. (only categories are combat/trade/construction
    def get_category_score(self, category):
        if category == "combat":
            fields = self.combat_attributes()
        elif category == "trade":
            fields = self.trade_attributes()
        elif category == "crafting":

apps/towns/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.core.context_processors import csrf
from django.shortcuts import get_object_or_404
from django.db import transaction

from apps.towns.models import Town, Tavern, TavernHero, OutskirtResource
from apps.towns.forms import buy_tavernhero, OutskirtForm
from apps.heroes.models import Hero



@login_required
def town_info(request, slug):
    town = get_object_or_404(Town, slug=slug)
    
    
    return render(request, "towns/town_info.html", {"town": town})
    




@login_required
@transaction.atomic
def tavern(request):
    town = get_object_or_404(Town, slug=request.session['town_slug'])
    #check if tavern heroes need a refresh
    town.tavern.check_for_refresh()
    heroes = town.tavern.tavernhero_set.all()
    
    if request.POST:
        result = buy_tavernhero(request.POST, request.user)
        return render(request, "tavern.html", {"heroes": heroes, "result": result})
        
    return render(request, "towns/tavern.html", {"heroes": heroes})
    
    

@login_required
def tavern_hero_info(request, tavernhero_id):
    tavernhero = get_object_or_404(TavernHero, pk=tavernhero_id)
    
    if request.POST:
        result = buy_tavernhero(request.POST, request.user)
        return render(request, "tavernhero.html", {"tavernhero": tavernhero, "result": result})
    
    return render(request, "towns/tavernhero.html", {"tavernhero": tavernhero})



@login_required
@transaction.atomic
def outskirts(request):
    town = get_object_or_404(Town, slug=request.session['town_slug'])
    town.outskirt.check_for_refresh()
    hero = Hero.objects.get(id=request.session["hero_id"])
    outskirts = town.outskirt.display_outskirts(hero.id)
    refresh_at = town.outskirt.refresh_at
    
    if request.POST:
        try:
            result = OutskirtForm.save_form(request.POST, request.session['hero_id'], request.POST['outskirt_id'])
        
        except KeyError:
            result = "Don't customize POST data"
        return render(request, "outskirts.html", {"hero": hero, "outskirts": outskirts, "refresh_at": refresh_at, "result": result})
    
    #make sure forms disapear for a hero that is active
    #chekc if hero is actif before submiting form
    
    return render(request, "towns/outskirts.html", {"hero": hero, "outskirts": outskirts, "refresh_at": refresh_at})
    
    

@login_required
def outskirt_info(request, outskirt_id):
    outskirt = get_object_or_404(OutskirtResource, pk=outskirt_id)
    hero = Hero.objects.get(id=request.session["hero_id"])
    outskirt_view = outskirt.display_outskirt(hero)
    outskirt_form = OutskirtForm(request.POST or request.session["hero_id"], outskirt, False)
    
    if request.POST:
        print request.POST
    
    return render(request, "towns/outskirt.html", {"hero": hero, "outskirt_view": outskirt_view, "outskirt_form": outskirt_form, "outskirt": outskirt})
    

apps/towns/templates/towns/outskirt.html
{% extends "base.html" %}
{% load towns_tags %}

{% block page_title %}Outskirt - {{ outskirt.resource.location }}{% endblock %}

{% block left_sidebar %}
    {% include "nav_bar.html" %}
{% endblock %}


{% block content %}
<div class="content_section">
    
    
    <div class="header_02">{{ outskirt_view.outskirt.resource.location }}</div>
    <p><strong>Quality: </strong>{{ outskirt_view.outskirt.get_quality_display }}</p>
    <p><strong>{{ outskirt_view.outskirt.resource.name }}: </strong>{{ outskirt_view.income }}</p>
    {% if outskirt_view.stamina_loss %}
    <p><strong>Stamina: </strong>{{ outskirt_view.loss }}</p>
    {% endif %}
    <p><strong>Room: </strong>
    {% if not outskirt_view.room %}
        <span style="color: red;">Full</span>
    {% else %}
        {{ outskirt_view.open_slots }}<br>
        
        {% if hero.active %}
        <p class="form_errors">Your hero is already at work.</p>
        {% else %}
        <form action="" method="POST">{% csrf_token %}
            {{ outskirt_form }}
            <input type="submit" value="Go to work">
        </form>
        {% endif %}
    {% endif %}
    </p>
    <br>
    <br>
    
    {% if outskirt.outskirtworker_set.all.count > 0 %}
    <p>Other players currently gathering resources at this location</p>
    
    <table>
        <tr>
            <th>User </th>
            <th>Finnished </th>
        </tr>
        {% for worker in outskirt.outskirtworker_set.all %}
        <tr>
            <td><a href="#">{{ worker.hero.user.username }}</a></td>
            <td>{{ worker.finnished_at }}</td>
        </tr>
        {% endfor %}
    </table>
    {% endif %}
    
    
        
        
    <div class="margin_bottom_20"></div>
</div>
            
{% endblock %}

apps/towns/templates/towns/outskirts.html
{% extends "base.html" %}
{% load towns_tags %}

{% block page_title %}{{ request.session.town_name }} - Outskirts{% endblock %}

{% block left_sidebar %}
    {% include "nav_bar.html" %}
{% endblock %}


{% block content %}
<div class="content_section">
    {{ request.session.town_name }} has resourcefull outskirts. You can use your hero to gather these resources.<br>
    These outskirts are available untill "{{ refresh_at }}"
    <br>
    <br>
    
    {% if result  %}
    {{ result }}
    <br>
    <br>
    {% endif %}
    
    {% for outskirt in outskirts %}
    <p style="font-size: 115%;"><a href="{% url 'outskirt_info' outskirt.outskirt.id %}">{{ outskirt.outskirt.resource.location }}</a></p>
    <p><strong>Quality: </strong>{{ outskirt.outskirt.get_quality_display }}</p>
    <p><strong>{{ outskirt.outskirt.resource.name }}: </strong>{{ outskirt.income }}</p>
    
    {% if outskirt.stamina_loss %}
    <p><strong>Stamina: </strong>{{ outskirt.loss }}</p>
    {% endif %}
    
    <p><strong>Room: </strong>
    
    {% if not outskirt.room %}
        <span style="color: red;">Full</span>
    {% else %}
        {{ outskirt.open_slots }}<br>
        {% if not hero.active %}
        <form action="" method="POST">{% csrf_token %}
            {{ outskirt.form }}
            <input type="hidden" name="outskirt_id" value="{{ outskirt.outskirt.id }}">
            <input type="submit" value="Go to work">
        </form>
        {% endif %}
    {% endif %}
    
    </p>
    <br><br>
    {% endfor %}

    TODO: <a href="http://www.w3schools.com/jquerymobile/tryit.asp?filename=tryjqmob_forms_slider">Make a slider for form input</a><br>
    
    
    <div class="margin_bottom_20"></div>
</div>
        
{% endblock %}

apps/towns/templates/towns/tavern.html
{% extends "base.html" %}
{% load users_tags %}

{% block page_title %}{{ request.session.town_name }} - Tavern{% endblock %}

{% block left_sidebar %}
    {% include "nav_bar.html" %}
{% endblock %}


{% block content %}
<div class="content_section">
    Welcome to the Tavern.
    There are always a selection of heroes available for hire. <br>
    Be sure to drop by regularly, a new selection of heroes will be available every 20 to 60 minutes.<br>
    <br>
    TODO:
    Make the different classes in tabs?<br>
    Give different qualities, different colors<br>
    <br>
    {% if result.error %}
        <p class="form_errors">{{ result.message }}</p>
    {% elif not result.error %}
        <p class="form_success">{{ result.message }}</p>
    {% endif %}
    <br>
    <form action="" method="post">{% csrf_token %}
    <table>
        <tr>
            <th><div class="header_03">Name </div></th>
            <th><div class="header_03">Combat </div></th>
            <th><div class="header_03">Trade </div></th>
            <th><div class="header_03">Crafting </div></th>
            <th colspan="3"><div class="header_03" style="text-align: left;">Price </div></th>
        </tr>
    {% for tavernhero in heroes %}
        <tr>
            <td>{{ tavernhero.hero.name }}</td>
            <td>{{ tavernhero.hero.view_combat_score }}</td>
            <td>{{ tavernhero.hero.view_trade_score }}</td>
            <td>{{ tavernhero.hero.view_crafting_score }}</td>
            <td>{{ tavernhero.price|munny }}</td>
            <td><a href="{% url 'tavern_hero_info' tavernhero.id %}">more info</a></td>
            <td><button type="submit" name="tavernhero_id" value="{{ tavernhero.id }}">BUY</button></td>
        </tr>
    {% endfor %}
    </table>
    </form>
    
    
    <div class="margin_bottom_20"></div>
</div>
            
{% endblock %}

apps/towns/templates/towns/tavernhero.html
{% extends "base.html" %}
{% load users_tags %}

{% block page_title %}{{ request.session.town_name }} - Tavern Hero Information{% endblock %}

{% block left_sidebar %}
    {% include "nav_bar.html" %}
{% endblock %}


{% block content %}
<div class="content_section">
    
    <div class="header_02">{{ tavernhero.hero.name }}</div>
    
    {% if result.error %}
        <p class="form_errors">{{ result.message }}</p>
    {% elif not result.error %}
        <p class="form_success">{{ result.message }}</p>
    {% endif %}
    
    <table>
    {% for attributes in tavernhero.hero.view_hero_attributes %}
        <tr>
            <th colspan="2"><br><div class="header_03" style="font-size: 150%; text-align: left;">{{ attributes.category|capfirst }}</div></th>
        </tr>
        {% for key, value in attributes.values.items %}
        <tr>
            <td>{{ key }}</td>
            <td>{{ value.get_quality_display }}</td>
        </tr>
        {% endfor %}
    {% endfor %}
    </table>
    <br>
    <br>
    <form action="" method="post">{% csrf_token %}
        <div class="header_03">Price </div>
        {{ tavernhero.price|munny }} <button type="submit" name="tavernhero_id" value="{{ tavernhero.id }}">BUY</button>
    </form>
    
    <br><br><br>
    
    
    <div class="margin_bottom_20"></div>
</div>
{% endblock %}

apps/towns/templates/towns/town_info.html
{% extends "base.html" %}

{% block page_title %}{{ request.session.town_name }} - Town Information{% endblock %}

{% block left_sidebar %}
    {% include "nav_bar.html" %}
{% endblock %}


{% block content %}
<div class="content_section">
    <div>
        <div class="header_02">{{ town.name }}</div>
    
        {{ town.description }}
    
        <table>
            <tr>
                <td colspan="2">{% if town.controlled %}Player {% else %}NPC {% endif %}Controlled</td>
            </tr>
            <tr>
                <td>Owner </td>
                <td>
                    {% if town.owner_player != None %}<a href="#">{{ town.owner_player.username }}</a>{% endif %}
                    {% if town.owner_npc != None %}<a href="#">{{ town.owner_npc.name }}</a>{% endif %}
                </td>
            </tr>
            <tr>
                <td>Difficulty</td>
                <td>{{ town.difficulty }}</td>
            </tr>
        </table>
    </div>
    <br><br>
    <div>
        <div class="header_02">Outskirts</div>
        <table>
            <tr>
                <th>Location: </th>
                <th>Resource: </th>
                <th>Room: </th>
            </tr>
            {% for outskirt in town.outskirt.outskirtresource_set.all %}
            <tr>
                <td><a href="{% url 'outskirt_info' outskirt.id %}">{{ outskirt.resource.location }}</a></td>
                <td>{{ outskirt.resource.name }}</td>
                <td>
                {% if 1 > outskirt.open_slots %}
                    <span style="color: red;">Full</span>
                {% else %}
                    <span>{{ outskirt.open_slots }} open slots</span>
                {% endif %}
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
    
    
    
    
    
    
    
    <div class="margin_bottom_20"></div>
</div>
{% endblock %}